# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: $(pool)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    ls
    sed -i '' -e 's/Caroline Chiari/$(name)/g' ./src/app/app.component.html
    sed -i '' -e 's/<ApplicationClientID>/$(clientId)/g' ./src/environments/environment.prod.ts
    sed -i '' -e 's/<AzureTenantID>/$(tenantId)/g' ./src/environments/environment.prod.ts
    sed -i '' -e 's,<ProductionRedirectURI>,$(prodRedirectURI),g' ./src/environments/environment.prod.ts
    sed -i '' -e 's,<APIGateway>,$(APIGateway),g' ./src/environments/environment.prod.ts
    sed -i '' -e 's,<AdminAPIGateway>,$(AdminAPIGateway),g' ./src/environments/environment.prod.ts
    npm install -g @angular/cli
    npm install
    ng build --prod
    curl -L https://aka.ms/downloadazcopy-v10-mac --output azcopy.zip && unzip -j azcopy.zip -d ./azcopy
    ./azcopy/azcopy copy './dist/CloudResumeTemplate/*' '$(websiteSAS)' --recursive=true
  displayName: 'npm install and build'

