# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: $(pool)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    sed -i s/Caroline Chiari/$(name)/ ./src/app/app.component.html
    sed -i s/<ApplicationClientID>/$(clientId)/ ./src/environments/environment.prod.ts
    sed -i s/<AzureTenantId>/$(tenantId)/ ./src/environments/environment.prod.ts
    sed -i s/<ProductionRedirectURI>/$(prodRedirectURI)/ ./src/environments/environment.prod.ts
    npm install -g @angular/cli
    npm install
    ng build --prod
    curl -L https://aka.ms/downloadazcopy-v10-mac --output azcopy.zip && unzip -j azcopy.zip -d ./azcopy
    ./azcopy/azcopy copy './dist/CloudResumeTemplate' '$(websiteSAS)' --recurse=true
  displayName: 'npm install and build'

